name: Build Docker Image UI

env:
  IMAGE: ghcr.io/${{github.repository}}/${{github.ref_name}}

on:
  push:
    paths:
      - apps/ui/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cp package-lock.json apps/ui
      - run: docker login -u ${{github.repository_owner}} -p ${{secrets.GITHUB_TOKEN}} ghcr.io
      - run: docker build -t ${{env.IMAGE}}:ui apps/ui
      - run: docker push ${{env.IMAGE}}:ui
